# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jorge Carrasco
title: Site Reliability Engineer
email: jorge@ittasks.work
website: ittasks.work

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: qbandev
github_username: qbandev
linkedin_username: jorgeacarrasco

# About Section
# about_title: About Me
about_profile_image: images/jacv.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jorge a SRE architect interested in innovation, implementation, and scale of new technology. I have been working with the cloud in different industries, agile is in my 🧬.

  I am most skilled in: <mark>SRE</mark> and <mark>DevOps</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Infura
        link: infura.io
        # link_text: boringcompany.com
        sub_title: Site Reliability Engineer
        caption: September 2022 - Present
        quote: >
          Solving 21st century problems by making game changing products in the web3
        description: | # this will include new lines to allow paragraphs
          Combine engineering experience and an innate drive to improve existing systems and processes, with the creativity to develop novel solutions to evolving challenges.
      - layout: left
        title: Kudelski IOT
        link: kudelski-iot.com
        # link_text: boringcompany.com
        sub_title: Site Reliability Engineer
        caption: May 2018 - August 2022
        quote: >
          Deploying and building *IoT* Services & Solutions, Secure by Design
        description: | # this will include new lines to allow paragraphs
          SRE engineer deploying multi cloud IOT security platform taking the ownership for selecting infrastructure tools, managing production changes, and determining emergency responses.
      - layout: left
        title: IE Business School
        link: ie.edu
        # link_text: boringcompany.com
        sub_title: Cloud Engineer
        caption: January 2011 - April 2018
        quote: >
          Moving forward the cloud and devops culture
        description: | # this will include new lines to allow paragraphs
          Create the bridge between development and operations by applying a software engineering mindset to system administration topics.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
